# Generated by Django 3.1.4 on 2021-01-01 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210101_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='max_points',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
