# Generated by Django 3.1.4 on 2021-01-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210101_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Online', 'Online')], max_length=128)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
    ]
