# Generated by Django 3.1.3 on 2021-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subject_ingredient_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='max_points',
            field=models.IntegerField(default=100),
        ),
    ]
