# Generated by Django 3.1.3 on 2021-01-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210102_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('task_points', models.IntegerField()),
                ('subject_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject_ingredient')),
            ],
        ),
    ]
