# Generated by Django 3.1.3 on 2021-01-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
