# Generated by Django 3.1.3 on 2021-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210113_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='returned',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=128),
        ),
    ]
