# Generated by Django 3.1.3 on 2021-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_task_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_points_max',
            field=models.IntegerField(default=0),
        ),
    ]
