# Generated by Django 3.1.3 on 2021-01-14 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_task_task_points_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='max_points',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
